GET http://localhost:8000/kube/cluster/workspaces/e9cea3fc-ee43-405a-b169-cebe2949a46b
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsImV4cGlyeSI6MTc1MDc3MjYzMywidXNlcklEIjoxfQ.Dd3OT_kV4hmLZ0kAeOOXDhSIFE3sD28d_6XMZOHZZDE