PUT http://localhost:8000/kube/clusters/list/1/update
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsImV4cGlyeSI6MTc0NzIyNzQ2OSwidXNlcklEIjoxfQ.P_A6ZCQ5XAowrggrtUy3doasY4j5-EqCY8LDIzjOcrY

{
    "cluster_name": "updated-cluster, snowhite",
    "provisioner": "aks",
    "kubeconfig_path": "/kubeconfig/new"
}