GET http://localhost:8000/kube/users/list/permission
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QzQGdtYWlsLmNvbSIsImV4cGlyeSI6MTc0OTA2NTk0OCwidXNlcklEIjo0fQ.O0iBHU70__6M7QXhA9eEwBYLJvoihiQHxOLxJJG3NYM