POST http://localhost:8000/kube/DR
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsImV4cGlyeSI6MTc0OTI0MzQ1MCwidXNlcklEIjoxfQ.P9fp7wei17jmLK08ubEhKbgSlgRwd5Peq5bewI5OlgE

{
    "source_cluster_id": 1,
    "destination_cluster_id": 2,
    "dr_type": "active-passive"
}