DELETE http://localhost:3000/events/2/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGFiYy5jb20iLCJleHBpcnkiOjE3NDY0ODQ3NTgsInVzZXJJRCI6MX0.R0P7Jd_QVj-rEmZ1Npux60KNc-k3PGoD6Zx6FHBdJSQ
