POST http://localhost:8000/kube/clusters/list
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsImV4cGlyeSI6MTc0OTM5MjMwNywidXNlcklEIjoxfQ.q9Zfi3OEXhUYIYxIyyAhKi-g_TZcADeMBFxNiPFl8u0

{
    "name": "clus-02",
    "provisioner": "nutanix",
    "region": "us-east-1",
    "workspace": "new_workspace",
    "kubeconfig_file_path": "/Users/sakshi.aherkar/.kube/config"
}