GET http://localhost:8000/kube/cluster/1/actions/launch-console
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsImV4cGlyeSI6MTc0NzAwOTcwNCwidXNlcklEIjoxfQ.1qiVYaEkHBSqsSA6HbsOZ_RJn5S2rEWvBwaoEbWcTdQ