GET http://localhost:8000/kube/cluster/1/actions/launch-console
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsImV4cGlyeSI6MTc0NzA1MzAxNCwidXNlcklEIjoxfQ.cDIzzU5mwhRx1yrdd9ZGiYNV2KdRKqDfAanXZdOxOrc