POST http://localhost:8000/kube/clusters/list
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsImV4cGlyeSI6MTc0NzY5MzAzNCwidXNlcklEIjoxfQ.Mcr41LxE90qUK7coImwd2FRfpynR1IWnMixAeNsydCI

{
    "cluster_name": "snowhite-II-admin",
    "provisioner": "Nutanix",
    "kubeconfig_path": "/kube/sample.conf"
}