POST http://localhost:8000/kube/clusters/list
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsImV4cGlyeSI6MTc0NzQ4OTQ1NSwidXNlcklEIjoyfQ.MFvbYA8ok_8FEKEiQaoEyzmmwm7TviUl06iC3QL8krQ

{
    "cluster_name": "snowhite",
    "provisioner": "Nutanix",
    "kubeconfig_path": "/kube/sample.conf"
}