GET http://localhost:8000/kube/cluster/actions/1/services
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsImV4cGlyeSI6MTc0OTA2ODk0NSwidXNlcklEIjoxfQ.dqkkuBjP3rtO05LuoPXiw16y8FYypwf3dMx5Xx_endI